// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvDFbr_fNsC1ptBq1odKQpbw6QBmCNQQk',
    appId: '1:538772024211:web:dad51648e0b75c3fe65666',
    messagingSenderId: '538772024211',
    projectId: 'fitnessapp-4ff28',
    authDomain: 'fitnessapp-4ff28.firebaseapp.com',
    storageBucket: 'fitnessapp-4ff28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUt3GGDD43wQDRDqh9TdxU4NDSA1RpLFs',
    appId: '1:538772024211:android:89373bfdd43d2c81e65666',
    messagingSenderId: '538772024211',
    projectId: 'fitnessapp-4ff28',
    storageBucket: 'fitnessapp-4ff28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5AcNKuH4FaljnBECcvMH5TBcclMVARHg',
    appId: '1:538772024211:ios:1466f15c54b1be3ae65666',
    messagingSenderId: '538772024211',
    projectId: 'fitnessapp-4ff28',
    storageBucket: 'fitnessapp-4ff28.firebasestorage.app',
    androidClientId: '538772024211-j432rvanf6p24k8ton1i518d7urbu6ra.apps.googleusercontent.com',
    iosClientId: '538772024211-7f0ef01sks02543le461de5tqu0sff5b.apps.googleusercontent.com',
    iosBundleId: 'com.codeforany.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5AcNKuH4FaljnBECcvMH5TBcclMVARHg',
    appId: '1:538772024211:ios:1466f15c54b1be3ae65666',
    messagingSenderId: '538772024211',
    projectId: 'fitnessapp-4ff28',
    storageBucket: 'fitnessapp-4ff28.firebasestorage.app',
    androidClientId: '538772024211-j432rvanf6p24k8ton1i518d7urbu6ra.apps.googleusercontent.com',
    iosClientId: '538772024211-7f0ef01sks02543le461de5tqu0sff5b.apps.googleusercontent.com',
    iosBundleId: 'com.codeforany.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvDFbr_fNsC1ptBq1odKQpbw6QBmCNQQk',
    appId: '1:538772024211:web:3dee59feaeb95a0ce65666',
    messagingSenderId: '538772024211',
    projectId: 'fitnessapp-4ff28',
    authDomain: 'fitnessapp-4ff28.firebaseapp.com',
    storageBucket: 'fitnessapp-4ff28.firebasestorage.app',
  );

}